### ISSUE TITLE
Please add the ipa file

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_video_app#1]
Is there a way, can you generate the ipa file and upload it under the release section, This would be greatly helpful. Thanks.

**Comment by nanoscopic** [comment]
I can do so yes, but it won't be signed. The ipa will then need to be signed to install it to your iOS device, or your iOS device would need to be jailbroken.

How does having an ipa file help? Do you not have access to a mac running xcode?

I have not yet updated ios_remote_provider to run on straight Linux, so you will still need a Mac right now to run it.

**Comment by sai-tirunagiri** [comment]
Yes, I have a resigner, which will sign the ipa against the certificates which I use, and I do have access to mac, I can load the project into xcode and change the signing & capabilities, now when we try to build, its asking an app to run and I am not sure what to be selected or is this the way it needs to be installed.

![image](https://user-images.githubusercontent.com/12015596/108036439-3c8c5a80-705e-11eb-905c-309c92c4365c.png)

and also, we managed to generate an ipa file using xcode archieve, when we installed the ipa on the device with iOS version 14.4, the app launches and crashes. is there any additional setting to look into.

Thank You!

**Comment by sai-tirunagiri** [comment]
also, when we build and run the ios_video_app, see the below error, is it expected to come?

```
2021-02-16 16:28:14.416194+0530 vidtest[24173:7283728] [unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2021-02-16 16:28:14.432565+0530 vidtest[24173:7283728] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager copyItemAtURL:toURL:options:error:]: destination URL is nil'
*** First throw call stack:
(0x1a898186c 0x1bd99cc50 0x1a9c77b28 0x104bbfa5c 0x1aac0e744 0x1aac12f70 0x1aac13334 0x1ab378c44 0x1ab3783f4 0x1ab3792f4 0x1ab38a8f4 0x1ab5b67f8 0x1aa7bd5c0 0x1ab338a08 0x1ab338d9c 0x1aae34e38 0x1b86ec3bc 0x1b8717d04 0x1b86fb4a0 0x1b87179c8 0x104f016c0 0x104f05000 0x1b8740250 0x1b873fee0 0x1b8740434 0x1a88fd76c 0x1a88fd668 0x1a88fc9cc 0x1a88f6a8c 0x1a88f621c 0x1c04c2784 0x1ab336ee8 0x1ab33c75c 0x104bbf800 0x1a85b66b0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager copyItemAtURL:toURL:options:error:]: destination URL is nil'
terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by sai-tirunagiri** [comment]
I was able to resolve the above but ended up with a new error as shown below on the **ViewController.m** line : 41

![image](https://user-images.githubusercontent.com/12015596/108059992-4c1a9c00-707c-11eb-97e9-f10b8206aa38.png)

**Comment by nanoscopic** [comment]
I've removed all the "shared file" / app group stuff. The original intent of that stuff was so that the app can be easily configured before streaming is started, but in the end it isn't used and just makes building the app much more difficult.

Now that it is removed, it should prevent users from seeing the error about wanting the config file, and it will make building the app easier as an "app group" is no longer needed.

I've additionally added Makefile rules into the ios_remote_provider repo for easily building / installing the ios_video_app on a device.

I attempted also to create an "unsigned ipa file". I have no idea of how to do this. I read a number of sites online and it is unclear. I can create an "unsigned xcarchive" ( there is a Makefile rule to do so ), and I made an attempt at creating an "unsigned ipa", but the ipa file created by doing that does not function on my jailbroken iphone.

As always I'd highly recommend avoiding jailbreaking and using official/normal signed apps.

I have an ipa file now, but it is signed for developer distribution against my setup. I don't wish to distribute a signed form as it contains private information ( such as the mobileprovision file, which contains UDID of my devices )

I can simply delete the mobileprovision files from the ipa and then potentially upload. The file then will still contain the signatures but that should be harmless... Considering...

**Comment by nanoscopic** [comment]
I've added a release that is a normally built IPA file with mobileprovision and _CodeSignature erased. Am curious if you will be able to resign and install it and have it work. If you manage to do so, please detail the steps followed to do so so that I can share them with others.

**Comment by sai-tirunagiri** [comment]
Thank you, Now am able to launch the app on the device, and sure, I will write the steps in how to resign the ipa.
