### ISSUE TITLE
Does this application need to change usb mode? 

### ISSUE THREAD

**Issue by tburakdemir** [nanoscopic/ios_video_app#4]
Hello,

I am currently using minicap via idb. It needs to change usb mode as you know. This side effect and some problems (can't start banner, stuck on startup etc.) hinder me. So when I was searching about this problem, I found your solution. So is this app needs to reset usb mode?
Thank you

**Comment by nanoscopic** [comment]
No, this app uses the standard upload broadcast feature that Apple provides and supports.

In that way it does not rely on hacky things such as the various stuff that utilize the h264 stream available from the alternate USB mode.

The problem with this repo is that it is not the current version of the app. I took all updates to the app closed source some time ago as I can't afford to have a company built around this and ControlFloor is no one is paying for them.

The last public change here has the following issues:

1. It uses nanomsg, which while fast and great on solid networks, tends to be buggy and hard to deal with when there is network packet loss. As a result, in the latest internal version I have, we migrated to straight TCP connectivity for this using a simple protocol, to make it more stable regardless of network conditions.

2. It has a few bugs in how it was written such that it leaks memory over time and thus will crash within 24 hours and the stream need to be restarted again. We have fixed all such issues in the current internal version, and that version runs indefinitely without crashing ( weeks... months... etc )

3. It can't adjust video resolution and framerate on the fly to adjust to conditions dynamically. The latest version has improvements both to how latency and bandwidth are measured, as well as being able to easily be adjusted to those conditions to give the best results.

4. On some devices this version will use too much CPU, causing iOS OS itself to terminate the extension. This also has of course been fixed in the internal version...

We ( Dry Ark LLC ) are currently in process of building out the website ( controlfloor.com; currently blank ), offering free trial versions of ControlFloor and this app that work together, as well as in outlining reasonable costs that compete with all the alternative products on the market. It will just take a bit of time, but that is our current focus, to enable those who want these things to finally actually purchase licenses for the latest and greatest.

Anyone who wishes is still welcome to continue with this legacy code and attempt to fix the issues on your own. I will happily accept such corrective PRs should the community wish to support this themselves to have a free option.
